spring:
  application:
  name: SynchronyProject

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-vxobzofzht7rh7if.us.auth0.com/
          audience: https://synchrony-project

  datasource:
    url: jdbc:h2:mem:syfdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect